### PR TITLE
Avoid to materialize cleartext password

### PR DESCRIPTION
**Pull request by Servox3**
Avoiding to materialize cleartext password when saving or loading a Credential object

### CODE REVIEW

**Comment by tts-sdrissen** [comment]
Why did you remove the boundary check?
[The MaxLength of SecurePassword is 65536 chars](https://learn.microsoft.com/en-us/dotnet/api/system.security.securestring.length?view=net-6.0#:~:text=The%20maximum%20length%20of%20a%20SecureString%20instance%20is%2065%2C536%20characters.), but the MaxLength for this field [CRED_MAX_CREDENTIAL_BLOB_SIZE is only 2560 (5*512) byte](https://learn.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credentiala#:~:text=CRED_MAX_CREDENTIAL_BLOB_SIZE%20(5*512)%20bytes.).

It would be possible to give a larger value than allowed.

**Comment by Servox3** [comment]
I wasn't aware of the CredentialBlob size limitation. However, when the Password property is accessed, like in the original code, the password will be created in plain text in memory as a String. This will compromise the security of the running application, so that is why I wanted to avoid accessing the Password property.

I assumed that an exception will be thrown anyway, if the CredentialBlob is to large, but I don't know if that is actually the case.

**Comment by tts-sdrissen** [comment]
The value of the Length property of a SecureString is calculated and saved as an integer, when a String is saved in a SecureString.
This means, the password is not materialized, when you use `SecurePassword.Length`.

Just for fun, I looked in the Microsoft Docs, but I cannot find, that an exception is thrown, when the Password is too long.
Maybe the exception is [ERROR_INVALID_PARAMETER](https://learn.microsoft.com/en-us/windows/win32/api/wincred/nf-wincred-credwritew#:~:text=ERROR_INVALID_PARAMETER).
I would not think, that this error came from a too long password.

Don't get me wrong! Your suggestion in general is very good. But @spolnik had a point to check the password length.

I changed it to this, because I am not entirely sure, what the MaxLength of (5*512) bytes actually means:
`            if (SecurePassword.Length * sizeof(char) > (512))
                throw new ArgumentOutOfRangeException("password", "The password has exceeded 512 bytes.");
`

Can we agree that that would be a good solution?

**Comment by tts-sdrissen** [comment]
Solved by [Pull Request #7](https://github.com/spolnik/Simple.CredentialsManager/pull/7)

**Pull request closed without merging**
